Fill general usage section in readme
yiisoft/form-model pull request #56
Opened 2024-08-21 13:10 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

2024-08-21 13:11 UTC, arogachev commented on README.md
> +```php
Show usage in controller.

2024-08-21 13:11 UTC, arogachev commented on README.md
> +```php
Show usage in the view.

2024-08-22 20:12 UTC, samdark approved these changes

2024-08-22 20:12 UTC, samdark commented on README.md
> +        // Display an error message.
Like this?

```suggestion
        // Display an error message.
        <p><?= Html::encode($errorMessage) ?></p>
```

2024-08-23 11:53 UTC, vjik requested changes

2024-08-23 11:53 UTC, vjik commented on README.md
> +    private bool $rememberMe = false;
```suggestion
    #[Required]
    #[Length(min: 4, max: 40, skipOnEmpty: true)]
    #[Email(skipOnEmpty: true)]
    private ?string $login = null;

    #[Required]
    #[Length(min: 8, skipOnEmpty: true)]
    private ?string $password = null;

    #[Safe]
    private bool $rememberMe = false;
```

2024-08-23 11:53 UTC, vjik commented on README.md
> +final class PostController
```suggestion
final class AuthController 
```

2024-08-23 11:53 UTC, vjik commented on README.md
> +        /** @var FormModel $formModel */
```suggestion
```

2024-08-23 11:53 UTC, vjik commented on README.md
> +Display it using [pure fields](docs/guide/en/pure-fields.md) in the view:
```suggestion
Display it using [fields](docs/guide/en/displaying-fields.md) in the view:
```

2024-08-23 13:34 UTC, vjik approved these changes

2024-08-23 17:04 UTC, merged